### ISSUE TITLE
Compatibility with php-translation/symfony-bundle 0.9

### ISSUE THREAD

**Issue by plutonio21** [Coffreo/php-translation-js-extractor-bundle#1]
Current stable version of `php-translation/symfony-bundle` is `0.9.1`, but `coffreo/php-translation-js-extractor-bundle` has a constraint of `^0.8.1`. Is it possible to fix this?

**Comment by emri99** [comment]
I'll try to fix this today ;)

**Comment by plutonio21** [comment]
> I'll try to fix this today ;)

Thanks a lot :)

**Comment by emri99** [comment]
Can you tell me if you experiment added empty translation when using this bundle with empty source and no line associated like sample below ?

```xml
    <unit id="47DEQpj" name="">
      <segment>
        <source></source>
        <target></target>
      </segment>
    </unit>
```

sidenote: this is not due to this issue update, I was also experimenting this before :(

**Comment by plutonio21** [comment]
I get this error since I started using php-translation, so it's not related
to your bundle

**Comment by emri99** [comment]
ok, Thanks for reply ;)

**Comment by plutonio21** [comment]
you're welcome :)
